DROP DATABASE IF EXISTS todo;
CREATE DATABASE todo CHARACTER SET utf8mb4;
DROP USER IF EXISTS 'user';
CREATE USER 'user' IDENTIFIED BY 'P@ssw0rd';
GRANT ALL PRIVILEGES ON todo.* to 'user';
USE todo;
SHOW DATABASES;
